/**
 * compose.ts — generates a standalone `docker-compose.yml` for operators who
 * installed via `npx @agenti-fy/setup` and never cloned the source repo.
 *
 * The generated file:
 *  - References published Docker images (`ghcr.io/<owner>/<package>:<tag>`)
 *    instead of local `build:` stanzas. The caller picks the tag — by
 *    default the wizard pins it to its own `package.json` version, so
 *    `npx @agenti-fy/setup@0.3.1 init` writes `:0.3.1` and the operator's
 *    coordinator + agent versions stay locked together.
 *  - Bind-mounts per-persona soul files from `./souls/<persona>.md`,
 *    matching the in-tree `docker-compose.yml`'s soul-mount semantics so
 *    operators retain full customizability. The wizard also writes those
 *    soul files (copied from the bundled defaults at `dist/souls/`) when
 *    it writes the compose, so the bind-mounts resolve.
 *  - Mirrors the in-tree compose's env-var fill-ins (`${VAR-}` for required
 *    secrets, `${VAR:-default}` for tunables) so the same `.env` works
 *    interchangeably.
 *
 * Coupling note: this file is hand-maintained against `docker-compose.yml`
 * at the repo root. When that file's structure changes (new env vars, new
 * services, new volume layout), this generator must follow. There is no
 * automatic drift detection — the regression tests in `compose.test.ts`
 * are the safety net.
 */

import { BUILTIN_PERSONAS, type BuiltinPersona } from '@agenti-fy/shared';

// ── Public surface ────────────────────────────────────────────────────────────

export interface RenderComposeOptions {
  /**
   * Image registry path WITHOUT trailing slash and WITHOUT the package name.
   * Defaults to `ghcr.io/agenti-fy`. Overridable for forks that publish to
   * a different registry or namespace.
   */
  imageRegistry?: string;
  /**
   * Image tag to pin both `coordinator` and `agent` to. Defaults to the
   * wizard's own `package.json` version (caller responsibility — pass via
   * `readPackageVersion(import.meta.url, 1)` from bin.ts).
   *
   * Operators who want `:latest` or to pin earlier can pass it explicitly
   * via the `--image-tag` CLI flag.
   */
  imageTag: string;
  /**
   * Include the optional monitoring profile (prometheus + grafana). Default
   * `false` — monitoring is opt-in and operators who want it can run
   * `docker compose --profile monitoring up`. Setting this to `true` doesn't
   * change the generated file's profile-gate; it only controls whether the
   * monitoring services are present in the file at all.
   */
  includeMonitoring?: boolean;
}

const DEFAULT_REGISTRY = 'ghcr.io/agenti-fy';

// ── renderer ──────────────────────────────────────────────────────────────────

/**
 * Build the docker-compose.yml content for a published-image deployment.
 *
 * Pure function — caller decides where to write the result. No filesystem
 * access. The output is byte-for-byte deterministic given the same inputs,
 * which keeps regression tests stable.
 */
export function renderCompose(opts: RenderComposeOptions): string {
  const registry = (opts.imageRegistry ?? DEFAULT_REGISTRY).replace(/\/+$/, '');
  const tag = opts.imageTag;
  const coordinatorImage = `${registry}/coordinator:${tag}`;
  const agentImage = `${registry}/agent:${tag}`;
  const includeMonitoring = opts.includeMonitoring ?? false;

  const personaServices = BUILTIN_PERSONAS.map((p) => personaService(p)).join('\n\n');
  const monitoringBlock = includeMonitoring ? MONITORING_BLOCK : '';
  const personaVolumes = BUILTIN_PERSONAS.map((p) => `  ${p}-workspace:\n  ${p}-claude:`).join('\n');

  return [
    HEADER_COMMENT.trim(),
    '',
    AGENT_ENV_ANCHOR.trim(),
    '',
    agentDefaultsAnchor(agentImage).trim(),
    '',
    'services:',
    coordinatorService(coordinatorImage).trim(),
    '',
    personaServices,
    monitoringBlock ? '' : '',
    monitoringBlock.trim(),
    '',
    'volumes:',
    '  coordinator-data:',
    personaVolumes,
    includeMonitoring ? '  prometheus-data:\n  grafana-data:' : '',
    '',
  ]
    .filter((s) => s !== null)
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd() + '\n';
}

// ── Templates ─────────────────────────────────────────────────────────────────

const HEADER_COMMENT = `
# docker-compose.yml — generated by \`npx @agenti-fy/setup\`.
#
# Pulls published images from GHCR rather than building locally. The
# coordinator and all nine persona agents come from the same image set,
# pinned to the wizard's own version at generation time.
#
# Bring up the production fleet:
#   docker compose up -d
#
# Bring up + monitoring (Prometheus + Grafana — only present when the
# wizard was run with monitoring enabled):
#   docker compose --profile monitoring up -d
#
# All env-var defaults match the in-tree \`docker-compose.yml\` shipped with
# the source repo at https://github.com/agenti-fy/core. To customize, edit
# this file or the adjacent \`.env\`.
`;

const AGENT_ENV_ANCHOR = `
x-agent-env: &agent-env
  # GitHub App credentials are SET PER-AGENT in each service's \`environment:\`
  # block — every persona uses its own App so commits, comments, and reviews
  # appear under that persona's bot identity (e.g. agenti-fy-tinkerer[bot]).

  # Anthropic. Pick ONE auth path:
  #   - CLAUDE_CODE_OAUTH_TOKEN — long-lived OAuth token from \`claude
  #     setup-token\` on a Max-subscription host. Preferred for headless fleets.
  #   - ANTHROPIC_API_KEY — classic sk-ant-* API key. Bills against API credits.
  CLAUDE_CODE_OAUTH_TOKEN: \${CLAUDE_CODE_OAUTH_TOKEN-}
  ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY-}
  CLAUDE_ADAPTER: \${CLAUDE_ADAPTER:-auto}
  CLAUDE_MAX_TURNS: \${CLAUDE_MAX_TURNS-}
  CLAUDE_MAX_TURNS_PLAN: \${CLAUDE_MAX_TURNS_PLAN-}
  CLAUDE_MAX_TURNS_IMPLEMENT: \${CLAUDE_MAX_TURNS_IMPLEMENT-}
  CLAUDE_MAX_TURNS_REVIEW: \${CLAUDE_MAX_TURNS_REVIEW-}
  CLAUDE_MAX_TURNS_ADDRESS_REVIEW: \${CLAUDE_MAX_TURNS_ADDRESS_REVIEW-}
  CLAUDE_MAX_TURNS_MERGE: \${CLAUDE_MAX_TURNS_MERGE-}
  CLAUDE_TIMEOUT_MS: \${CLAUDE_TIMEOUT_MS:-900000}
  CLAUDE_COST_LIMIT_USD: \${CLAUDE_COST_LIMIT_USD:-5.0}

  # Where to find the coordinator.
  COORDINATOR_URL: \${COORDINATOR_URL:-http://coordinator:8080}
  COORDINATOR_TIMEOUT_MS: \${COORDINATOR_TIMEOUT_MS:-15000}

  # Boot retry + heartbeat cadence.
  REGISTER_RETRY_MS: \${REGISTER_RETRY_MS:-2000}
  REGISTER_MAX_ATTEMPTS: \${REGISTER_MAX_ATTEMPTS:-60}
  HEARTBEAT_INTERVAL_MS: \${HEARTBEAT_INTERVAL_MS:-15000}

  # Agent-local state.
  SOUL_PATH: \${SOUL_PATH:-/etc/agentify/SOUL.md}
  WORKSPACES_DIR: \${WORKSPACES_DIR:-/workspaces}
  JOB_HISTORY_CAPACITY: \${JOB_HISTORY_CAPACITY:-500}

  # Logging.
  LOG_LEVEL: \${LOG_LEVEL:-info}

  # Offline-dev escape hatch — accepts 1/true/yes/on (true) or
  # 0/false/no/off/empty (false). Anything else falls back to false.
  DISABLE_GITHUB: \${DISABLE_GITHUB:-false}

  # Knowledge base (KB).
  KB_ENABLED: \${KB_ENABLED:-true}
  KB_GLOBAL_PAGE: \${KB_GLOBAL_PAGE:-KB-Global}
  KB_PAGE_PREFIX: \${KB_PAGE_PREFIX:-KB-}
  KB_WRITE_RETRY_MAX: \${KB_WRITE_RETRY_MAX:-3}
  KB_ENTRY_MAX_BYTES: \${KB_ENTRY_MAX_BYTES:-1024}
`;

function agentDefaultsAnchor(agentImage: string): string {
  return `
x-agent-defaults: &agent-defaults
  image: ${agentImage}
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: \${AGENT_MEMORY_LIMIT:-1024M}
  healthcheck:
    test: ["CMD", "node", "-e", "fetch('http://localhost:8080/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
    interval: 15s
    timeout: 5s
    retries: 3
    start_period: 20s
  depends_on:
    coordinator:
      condition: service_healthy
`;
}

function coordinatorService(coordinatorImage: string): string {
  return `
  coordinator:
    image: ${coordinatorImage}
    restart: unless-stopped
    environment:
      # GitHub App.
      GITHUB_APP_ID: \${GITHUB_APP_ID}
      GITHUB_APP_PRIVATE_KEY: \${GITHUB_APP_PRIVATE_KEY}
      GITHUB_APP_INSTALLATION_ID: \${GITHUB_APP_INSTALLATION_ID}
      GITHUB_USER: \${GITHUB_USER}

      # HTTP server.
      PORT: \${COORDINATOR_PORT:-8080}
      HOST: \${COORDINATOR_HOST:-0.0.0.0}

      # State.
      DATA_DIR: \${DATA_DIR:-/data}

      # Polling + dispatch loops.
      DEFAULT_POLL_INTERVAL_S: \${DEFAULT_POLL_INTERVAL_S:-30}
      WORK_POLL_S: \${WORK_POLL_S:-30}
      JOB_COMPLETION_POLL_S: \${JOB_COMPLETION_POLL_S:-5}
      INSTALLATION_REFRESH_S: \${INSTALLATION_REFRESH_S:-300}

      # Plan-completion poller.
      PLAN_COMPLETION_POLL_S: \${PLAN_COMPLETION_POLL_S:-60}

      # Stuck-issue rescue.
      STALE_JOB_TIMEOUT_S: \${STALE_JOB_TIMEOUT_S:-1800}
      STALE_JOB_SWEEP_S: \${STALE_JOB_SWEEP_S:-600}

      # Result-payload size cap (bytes). Oversize results are recorded as task_error.
      MAX_RESULT_JSON_BYTES: \${MAX_RESULT_JSON_BYTES:-262144}

      # Job-row GC retention.
      FAILED_DISPATCH_RETENTION_DAYS: \${FAILED_DISPATCH_RETENTION_DAYS:-7}
      COMPLETED_JOB_RETENTION_DAYS: \${COMPLETED_JOB_RETENTION_DAYS:-30}

      # Logging.
      LOG_LEVEL: \${LOG_LEVEL:-info}

      DISABLE_GITHUB: \${DISABLE_GITHUB:-false}
    volumes:
      - coordinator-data:/data
    ports:
      - "\${COORDINATOR_HOST_PORT:-8080}:8080"
    deploy:
      resources:
        limits:
          memory: \${COORDINATOR_MEMORY_LIMIT:-512M}
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8080/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
`;
}

/**
 * Per-persona service block. Every persona uses the same shape — the only
 * differences are the env-var prefix (`<UPPERCASE_PERSONA>_GITHUB_APP_*`) and
 * the bind-mount source (`./souls/<persona>.md`). Iterated by the renderer
 * so adding/removing a persona only touches `BUILTIN_PERSONAS`.
 */
function personaService(persona: BuiltinPersona): string {
  const upper = persona.toUpperCase();
  return `  ${persona}:
    <<: *agent-defaults
    environment:
      <<: *agent-env
      AGENT_PUBLIC_URL: \${${upper}_PUBLIC_URL:-http://${persona}:8080}
      GITHUB_APP_ID: \${${upper}_GITHUB_APP_ID}
      GITHUB_APP_INSTALLATION_ID: \${${upper}_GITHUB_APP_INSTALLATION_ID}
      GITHUB_APP_PRIVATE_KEY: \${${upper}_GITHUB_APP_PRIVATE_KEY}
      GITHUB_USER: \${${upper}_GITHUB_USER}
    volumes:
      - ./souls/${persona}.md:/etc/agentify/SOUL.md:ro
      - ${persona}-workspace:/workspaces
      # Persisted Claude Code SDK conversation store so cached session_ids
      # stay valid across \`docker compose up\` recreates.
      - ${persona}-claude:/app/.claude`;
}

const MONITORING_BLOCK = `
  # ─── Optional monitoring stack ────────────────────────────────────────────
  # Enable with \`--profile monitoring\`. Scrapes /metrics from coordinator and
  # every agent.
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "\${PROMETHEUS_HOST_PORT:-9090}:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "\${GRAFANA_HOST_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: \${GRAFANA_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    profiles:
      - monitoring
`;
