/**
 * env-renderer.ts — render a .env file from a validated WizardConfig.
 *
 * PEM private keys are written as single-quoted multi-line blocks so they
 * round-trip through `docker compose --env-file` parsing without mangling.
 * The output order mirrors docker-compose.yml's anchor groupings:
 *   1. Coordinator block (GITHUB_APP_*)
 *   2. Anthropic credentials
 *   3. Nine per-persona blocks (in BUILTIN_PERSONAS order)
 *   4. Optional tunables (pass-through key=value pairs)
 */

import { z } from 'zod';
import { BUILTIN_PERSONAS } from '@agentify/shared';

// ── Schemas ───────────────────────────────────────────────────────────────

const NonEmptyString = z.string().min(1, 'must be a non-empty string');

const AppCredentialsSchema = z.object({
  appId: NonEmptyString,
  installationId: NonEmptyString,
  privateKey: NonEmptyString,
  githubUser: NonEmptyString,
});

const AnthropicSchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('api_key'), value: NonEmptyString }),
  z.object({ kind: z.literal('oauth_token'), value: NonEmptyString }),
]);

/**
 * Tunable keys must be valid upper-case environment variable identifiers so
 * that a key containing `\n` or `=` cannot inject extra lines into the
 * generated .env file.  Operator-supplied values are still unrestricted.
 */
const TunableKeySchema = z
  .string()
  .regex(
    /^[A-Z_][A-Z0-9_]*$/,
    'tunable keys must be uppercase environment variable names ([A-Z_][A-Z0-9_]*)',
  );

const TunablesSchema = z
  .record(TunableKeySchema, z.union([z.string(), z.number()]).optional())
  .optional();

const PersonasSchema = z.object(
  Object.fromEntries(BUILTIN_PERSONAS.map((p) => [p, AppCredentialsSchema])) as {
    [K in (typeof BUILTIN_PERSONAS)[number]]: typeof AppCredentialsSchema;
  },
);

export const WizardConfigSchema = z.object({
  prefix: NonEmptyString,
  repo: z.object({ owner: NonEmptyString, name: NonEmptyString }),
  coordinator: AppCredentialsSchema,
  personas: PersonasSchema,
  anthropic: AnthropicSchema,
  tunables: TunablesSchema,
});

/** Fully-validated wizard configuration produced by the setup driver. */
export type WizardConfig = z.infer<typeof WizardConfigSchema>;

/** Options for renderEnv — primarily exposed for deterministic testing. */
export interface RenderEnvOptions {
  /** Override the ISO timestamp written in the file header. Defaults to `new Date().toISOString()`. */
  timestamp?: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────

/**
 * Quote a value for inclusion in a docker-compose-compatible .env file.
 *
 * - Strings containing newlines (e.g. PEM keys) are written as single-quoted
 *   multi-line blocks; any embedded single-quotes are POSIX-escaped.
 * - Single-line values that contain special characters (spaces, `"`, `#`, `$`,
 *   `\`) are double-quoted with minimal escaping.
 * - All other values are left unquoted.
 */
function quoteValue(raw: string): string {
  if (raw.includes('\n')) {
    // Single-quoted multi-line block: POSIX-escape any embedded single-quotes.
    const escaped = raw.replace(/'/g, "'\\''");
    return `'${escaped}'`;
  }
  if (/[\s'"#$\\]/.test(raw)) {
    const escaped = raw.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  }
  return raw;
}

function kv(key: string, value: string): string {
  return `${key}=${quoteValue(value)}`;
}

/** Render a section separator comment, right-padding with ─ to column 72. */
function separator(label: string): string {
  const prefix = `# ── ${label} `;
  const padLen = Math.max(0, 72 - prefix.length);
  return `${prefix}${'─'.repeat(padLen)}`;
}

// ── Renderer ──────────────────────────────────────────────────────────────

/**
 * Render a .env file string from a validated WizardConfig.
 *
 * The returned string starts with a generated-file comment block, then lists
 * all required variables in the order docker-compose.yml references them.
 * Multi-line PEM values are written as single-quoted blocks so they survive
 * `docker compose --env-file` parsing without mangling.
 *
 * @throws {z.ZodError} if `config` does not satisfy WizardConfigSchema.
 */
export function renderEnv(config: WizardConfig, opts: RenderEnvOptions = {}): string {
  // Re-validate defensively so callers can pass plain objects.
  const parsed = WizardConfigSchema.parse(config);

  const timestamp = opts.timestamp ?? new Date().toISOString();
  const lines: string[] = [];

  // ── Header ───────────────────────────────────────────────────────────────
  lines.push(
    `# Generated by agentify-setup at ${timestamp}. Re-run \`agentify-setup verify\` to validate.`,
    '',
  );

  // ── Coordinator block ─────────────────────────────────────────────────────
  lines.push(separator('Coordinator'));
  lines.push(kv('GITHUB_APP_ID', parsed.coordinator.appId));
  lines.push(kv('GITHUB_APP_PRIVATE_KEY', parsed.coordinator.privateKey));
  lines.push(kv('GITHUB_APP_INSTALLATION_ID', parsed.coordinator.installationId));
  lines.push(kv('GITHUB_USER', parsed.coordinator.githubUser));
  lines.push('');

  // ── Anthropic credentials ─────────────────────────────────────────────────
  lines.push(separator('Anthropic'));
  if (parsed.anthropic.kind === 'api_key') {
    lines.push(kv('ANTHROPIC_API_KEY', parsed.anthropic.value));
  } else {
    lines.push(kv('CLAUDE_CODE_OAUTH_TOKEN', parsed.anthropic.value));
  }
  lines.push('');

  // ── Per-persona blocks (BUILTIN_PERSONAS order) ───────────────────────────
  for (const personaName of BUILTIN_PERSONAS) {
    const prefix = personaName.toUpperCase();
    const creds = parsed.personas[personaName];
    lines.push(separator(prefix));
    lines.push(kv(`${prefix}_GITHUB_APP_ID`, creds.appId));
    lines.push(kv(`${prefix}_GITHUB_APP_INSTALLATION_ID`, creds.installationId));
    lines.push(kv(`${prefix}_GITHUB_APP_PRIVATE_KEY`, creds.privateKey));
    lines.push(kv(`${prefix}_GITHUB_USER`, creds.githubUser));
    lines.push('');
  }

  // ── Tunables (optional pass-through) ─────────────────────────────────────
  if (parsed.tunables !== undefined) {
    const entries = Object.entries(parsed.tunables).filter(
      ([, v]) => v !== undefined,
    ) as [string, string | number][];
    if (entries.length > 0) {
      lines.push(separator('Tunables'));
      for (const [key, value] of entries) {
        lines.push(kv(key, String(value)));
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}
